AspNetCoreIdentity.Web/ViewModels/PasswordChangeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreIdentity.Web.ViewModels
{
    public class PasswordChangeViewModel
    {
        [DataType(DataType.Password)]
        [Display(Name = "Mevcut Şifreniz")]
        [MinLength(6, ErrorMessage = "Şifreniz en az 6 karakter içermelidir.")]
        [Required(ErrorMessage = "Mevcut Şifre alanı boş geçilemez.")]
        public  string PasswordOld { get; set; }
        [DataType(DataType.Password)]
        [Display(Name = "Yeni Şifre")]
        [MinLength(6, ErrorMessage = "Şifreniz en az 6 karakter içermelidir.")]
        [Required(ErrorMessage = "Yeni Şifre alanı boş geçilemez.")]
        public string PasswordNew { get; set; }
        [DataType(DataType.Password)]
        [Compare(nameof(PasswordNew), ErrorMessage = "Şifreler birbiriyle aynı değil.")]
        [Display(Name = "Yeni Şifre Tekrar")]
        [Required(ErrorMessage = "Yeni Şifre tekrar alanı boş geçilemez.")]
        [MinLength(6,ErrorMessage ="Şifreniz en az 6 karakter içermelidir.")]
        public string PasswordNewConfirm { get; set; }
    }
}

AspNetCoreIdentity.Web/ViewModels/UserEditViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreIdentity.Web.ViewModels
{
    public class UserEditViewModel
    {
        [Display(Name = "Kullanıcı Adı")]

        public string Username { get; set; }
        [Display(Name = "Email")]
       
        [EmailAddress(ErrorMessage = "Email formatı yanlış.")]
        public string Email { get; set; }
        [Display(Name = "Telefon")]
        
        public string Phone { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Doğum Tarihi")]
        public DateTime BirthDate { get; set; }
        [Display(Name = "Şehir")]
        public string City { get; set; }

        [Display(Name = "Profil Resmi")]
        public IFormFile Picture { get; set; }

        [Display(Name = "Cinsiyet")]
        public string Gender { get; set; }

        [Display(Name = "Hakkında")]
        public string About { get; set; }



    }
}

AspNetCoreIdentity.Web/Controllers/MemberController.cs
using AspNetCoreIdentity.Web.Extensions;
using AspNetCoreIdentity.Web.Models;
using AspNetCoreIdentity.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AspNetCoreIdentity.Web.Controllers
{
    [Authorize]
    public class MemberController : Controller
    {
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;

        public MemberController(SignInManager<AppUser> signInManager, UserManager<AppUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.FindByNameAsync(User.Identity!.Name!);
            var userViewModel = new UserViewModel
            {
                Email = currentUser!.Email,
                Username = currentUser!.UserName,
                PhoneNumber = currentUser!.PhoneNumber
            };
            return View(userViewModel!);
        }
        public async Task<IActionResult> PasswordChange()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> PasswordChange(PasswordChangeViewModel request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var currentUser = await _userManager.FindByNameAsync(User.Identity.Name);
            var checkOldPasssword = await _userManager.CheckPasswordAsync(currentUser,request.PasswordOld);
            if (!checkOldPasssword)
            {
                ModelState.AddModelError(String.Empty, "Eski şifreniz doğru değil.");
                return View();
            }
            var resultChangePassword = await _userManager.ChangePasswordAsync(currentUser,request.PasswordOld,request.PasswordNew);
            if (!resultChangePassword.Succeeded)
            {
                ModelState.AddModelErrorList(resultChangePassword.Errors.Select(x => x.Description).ToList());
                return View();
            }
            TempData["SuccessMessage"] = "Şifreniz başarıyla değiştirilmiştir.";
            await _userManager.UpdateSecurityStampAsync(currentUser);
            await _signInManager.SignOutAsync();
            await _signInManager.PasswordSignInAsync(currentUser, request.PasswordNew,true,false);

            return View();
        }
        public async Task LogOut()
        {
            await _signInManager.SignOutAsync();

        }
        public async Task<IActionResult> UserEdit()
        {
            var currentUser = (await _userManager.FindByNameAsync(User!.Identity!.Name!))!;
            var userEditViewModel = new UserEditViewModel()
            {
                Username = currentUser.UserName!,
                Email = currentUser.Email!,
                Phone = currentUser.PhoneNumber!,
             
                City = currentUser.City!,
                Gender = currentUser.Gender!,
          

            };
            
            return View(userEditViewModel);
        }
    }
}

AspNetCoreIdentity.Web/Views/Member/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@model UserViewModel

<section style="background-color: #eee;">
    <div class="container py-5">
        <div class="row">
            <div class="col">
                <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
                    <ol class="breadcrumb mb-0">
                        <li class="breadcrumb-item"><a href="#">Anasayfa</a></li>
                        <li class="breadcrumb-item"><a href="/Member/Index/">Ayarlar</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Kullanıcı Profili</li>
                    </ol>
                </nav>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-4">
                <div class="card mx-4">
                    <div class="card-body text-center">
                        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar"
                             class="rounded-circle img-fluid " style="width: 200px;">
                        <h5 class="my-3">@User.Identity.Name</h5>
                        <p class="text-muted mb-1">Full Stack Developer</p>
                        <p class="text-muted mb-4">Bay Area, San Francisco, CA</p>
                        <div class="d-flex justify-content-center mb-2">
                            <a href="/Member/PasswordChange/" class="btn btn-primary">Şifre Değiştir</a>
                            <a href="/Member/UserEdit/" class="btn btn-primary">Kullanıcı Bilgileri</a>
                           
                        </div>
                    </div>
                </div>
                <div class="card mb-4 mb-lg-0">
                    <div class="card-body p-0">
                        <ul class="list-group list-group-flush rounded-3">
                            <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                <i class="fas fa-globe fa-lg text-warning"></i>
                                <p class="mb-0">https://mdbootstrap.com</p>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                <i class="fab fa-github fa-lg" style="color: #333333;"></i>
                                <p class="mb-0">mdbootstrap</p>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>
                                <p class="mb-0"></p>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
                                <p class="mb-0">mdbootstrap</p>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
                                <p class="mb-0">mdbootstrap</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Kullanıcı Adı</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">@Model.Username</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Email</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">@Model.Email</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Telefon Numarası</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">@Model.PhoneNumber</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Mobile</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">(098) 765-4321</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Address</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">Bay Area, San Francisco, CA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="card mb-4 mb-md-0">
                            <div class="card-body">
                                <p class="mb-4">
                                    <span class="text-primary font-italic me-1">assigment</span> Project Status
                                </p>
                                <p class="mb-1" style="font-size: .77rem;">Web Design</p>
                                <div class="progress rounded" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80"
                                         aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
                                <div class="progress rounded" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
                                         aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
                                <div class="progress rounded" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
                                         aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
                                <div class="progress rounded" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
                                         aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
                                <div class="progress rounded mb-2" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                                         aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card mb-4 mb-md-0">
                            <div class="card-body">
                                <p class="mb-4">
                                    <span class="text-primary font-italic me-1">assigment</span> Project Status
                                </p>
                                <p class="mb-1" style="font-size: .77rem;">Web Design</p>
                                <div class="progress rounded" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80"
                                         aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
                                <div class="progress rounded" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
                                         aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
                                <div class="progress rounded" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
                                         aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
                                <div class="progress rounded" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
                                         aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
                                <div class="progress rounded mb-2" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                                         aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

AspNetCoreIdentity.Web/Views/Member/PasswordChange.cshtml
@model PasswordChangeViewModel
@{
    ViewData["Title"] = "PasswordChange";
}
@if (TempData["SuccessMessage"] != null)
{
    <div class="row col-5 offset-7 ">
        <div class="alert alert-success alert-dismissible fade show ">
            <strong>İşlem Başarılı!</strong> @TempData["SuccessMessage"]
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    </div>
}
<div class="row col-5 offset-7 ">
    <div class="alert alert-danger alert-dismissible fade show " asp-validation-summary="ModelOnly">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
</div>
<section style="background-color: #eee;">
    <div class="container py-5">
        <div class="row">
            <div class="col">
                <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
                    <ol class="breadcrumb mb-0">
                        <li class="breadcrumb-item"><a href="#">Anasayfa</a></li>
                        <li class="breadcrumb-item"><a href="/Member/Index/">Ayarlar</a></li>
                        <li class="breadcrumb-item active" href="/Member/PasswordChange/" aria-current="page">Şifre Değiştir</li>
                    </ol>
                </nav>
            </div>
        </div>

        <div class="row">
         
            </div>
            <div class="col-lg-12 ">
            <section class="" style="background-color: #eee; height:83vh; ">
                <div class="container h-100">
                    <div class="row d-flex justify-content-center align-items-center h-100">
                        <div class="col-lg-12 col-xl-11">
                            <div class="card text-black" style="border-radius: 25px; padding:1rem">
                                <div class="card-body p-md-5">

                                    <div class="row justify-content-center align-items-center">
                                        <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-1">
                                            <img src="~/images/Change-password.png" class="img-fluid h-75" alt="Sample image" />


                                        </div>
                                        <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-2">

                                            <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Şifre Değiştir</p>


                                            <form asp-controller="Member" asp-action="PasswordChange" method="post" class="mx-1 mx-md-4">


                                                <div class="d-flex flex-row align-items-center mb-4">
                                                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                                    <div class="form-outline flex-fill mb-0">
                                                        <label class="form-label" for="PasswordOld" asp-for="PasswordOld"></label>
                                                        <input type="password" id="PasswordOld" class="form-control" asp-for="PasswordOld" />
                                                        <span class="text-danger" asp-validation-for="PasswordOld"></span>
                                                    </div>
                                                </div>

                                                <div class="d-flex flex-row align-items-center mb-4">
                                                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                                                    <div class="form-outline flex-fill mb-0">
                                                        <label class="form-label" for="PasswordNew" asp-for="PasswordNew"></label>
                                                        <input type="password" id="PasswordNew" class="form-control" asp-for="PasswordNew" />
                                                        <span class="text-danger" asp-validation-for="PasswordNew"></span>
                                                    </div>
                                                </div>
                                                <div class="d-flex flex-row align-items-center mb-4">
                                                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                                    <div class="form-outline flex-fill mb-0">
                                                        <label class="form-label" for="PasswordNewConfirm" asp-for="PasswordNewConfirm"></label>
                                                        <input type="password" id="PasswordNewConfirm" class="form-control" asp-for="PasswordNewConfirm" />
                                                        <span class="text-danger" asp-validation-for="PasswordNewConfirm"></span>
                                                    </div>
                                                </div>


                                                <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                                    <button type="submit" class="btn btn-primary btn-lg">Şifreyi Değiştir</button>
                                                </div>

                                            </form>

                                        </div>
                                     
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            </div>
        </div>
    </div>
</section>

AspNetCoreIdentity.Web/Views/Member/UserEdit.cshtml
@model UserEditViewModel
@{
    ViewData["Title"] = "UserEdit";
}
<head>
    <link rel="stylesheet" type="text/css" href="~/css/UserEdit.css">
</head>


<section style="background-color: #eee;">
    <div class="container py-5">
        <div class="row">
            <div class="col">
                <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
                    <ol class="breadcrumb mb-0">
                        <li class="breadcrumb-item"><a href="#">Anasayfa</a></li>
                        <li class="/Member/Index/"><a href="/Member/Index/">Ayarlar</a></li>
                        <li class="breadcrumb-item active" href="/Member/UserEdit/" aria-current="page">Kullanıcı Bilgileri </li>
                    </ol>
                </nav>
            </div>
        </div>

        <div class="row mt-4">
            <div class="col-lg-3">
                <div class="card h-100">
                    <div class="card-body">
                        <div class="account-settings">
                            <div class="user-profile">
                                <div class="user-avatar">
                                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="">
                                </div>
                                <h5 class="user-name">Username</h5>
                                <h6 class="user-email">Email</h6>
                            </div>
                            <div class="about">
                                <h5>Hakkında</h5>
                                <p>About</p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-lg-9">
                <div class="card h-100">
                    <div class="card-body">
                        <form asp-controller="Member" asp-action="UserEdit" method="post" enctype="multipart/form-data">
                            <div class="row gutters">
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                    <h6 class="mb-2 text-primary">Kullanıcı Bilgileri</h6>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    <div class="form-group">
                                        <label class="form-label" for="Username" asp-for="Username"></label>
                                        <input type="text" id="Username" class="form-control" asp-for="Username" />
                                        <span class="text-danger" asp-validation-for="Username"></span>
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    <div class="form-group">
                                        <label class="form-label" for="Email" asp-for="Email"></label>
                                        <input type="text" id="Email" class="form-control" asp-for="Email" />
                                        <span class="text-danger" asp-validation-for="Email"></span>
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    <div class="form-group">
                                        <label class="form-label" for="Phone" asp-for="Phone"></label>
                                        <input type="text" id="Phone" class="form-control" asp-for="Phone" />
                                        <span class="text-danger" asp-validation-for="Phone"></span>
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-6">
                                    <div class="form-group">
                                        <label class="form-label" for="BirthDay" asp-for="BirthDate"></label>
                                        <input type="date" id="BirthDay" class="form-control" asp-for="BirthDate" />
                                        <span class="text-danger" asp-validation-for="BirthDate"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row gutters">

                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    <div class="form-group">
                                        <label class="form-label" for="City" asp-for="City"></label>
                                        <input type="datetime" id="City" class="form-control" asp-for="City" />
                                        <span class="text-danger" asp-validation-for="City"></span>
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12 ">
                                    <div class="form-group">
                                        <label class="form-label" for="Picture" asp-for="Picture"></label>
                                        <input type="file" id="Picture" class="form-control" asp-for="Picture" />
                                        <span class="text-danger" asp-validation-for="Picture"></span>
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    <div class="form-group">
                                        <label class="form-label" for="Gender" asp-for="Gender"></label>
                                        <select  id="Gender" class="form-control" asp-for="Gender" >
                                        <option selected>Seçiniz</option>
                                        <option value="Erkek">Erkek</option>
                                        <option value="Kadin">Kadın</option>
                                        <option value="Belirtilmemiş">Belirtmek istemiyorum</option> </select>
                                        <span class="text-danger" asp-validation-for="Gender"></span>
                                    </div>
                                </div>


                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-6 ">
                                    <div class="form-group">
                                        <label class="form-label" for="About" asp-for="About"></label>
                                        <input rows="3" type="text" id="About" class="form-control" asp-for="About" />
                                        <span class="text-danger" asp-validation-for="About"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row gutters">
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 mt-3">
                                    <div class="text-right">
                                        <button type="button" id="submit" name="submit" class="btn btn-secondary">Cancel</button>
                                        <button type="button" id="submit" name="submit" class="btn btn-primary">Update</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>